server:
  port: 8080
  servlet:
    context-path: /smalldoc-demo

spring:
  application:
    name: smalldoc-demo
---
smalldoc:
  enabled: true #默认是true
  source-paths: # 额外的源码路径（项目的源码路径默认已经包含在内，不需要再添加）
    - D:\workspace\springboot\smalldoc-demo\src\main\java
  packages: #需要对外暴露接口或实体的包的位置
    - com.example.smalldocdemo.controller
    - com.example.smalldocdemo.model.feo
    - com.example.smalldocdemo.model.vo
  project-name: 我的接口文档
  url-pattern: /smalldoc/* #默认为/smalldoc/*