server:
  port: 8080

spring:
  application:
    name: project-demo
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://bj-cdb-jllri4sg.sql.tencentcdb.com:62645/varys_db_dev?characterEncoding=UTF-8&useSSL=false
    username: varys
    password: varys12321